import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
async function getUser(req:Request){const a=req.headers.get('Authorization');if(!a)return null;const c=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:a}}});return (await c.auth.getUser()).data.user||null;}
async function isAdmin(id:string,d:any){return !!(await d.from('profiles').select('is_admin').eq('id',id).maybeSingle()).data?.is_admin;}
function parseId(v:string){const x=v.trim();if(/^[A-Za-z0-9_-]{11}$/.test(x))return x;try{const u=new URL(x);if(u.hostname==='youtu.be')return u.pathname.slice(1).split('/')[0]||null;if(u.hostname.endsWith('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v');if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||null;if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||null}}catch{}return null;}
async function ytMeta(id:string){const w=`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`;const r=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(w)}&format=json`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('YouTube video could not be resolved.');const o=await r.json() as any;let h='';try{const p=await fetch(w,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'en-US,en;q=0.9'}});if(p.ok)h=await p.text()}catch{}const duration=Number(h.match(/\\\"lengthSeconds\\\"\\s*:\\s*\\\"(\\d+)\\\"/i)?.[1]||h.match(/\\\"lengthSeconds\\\"\\s*:\\s*(\\d+)/i)?.[1]||0);const live=/(\\\"isLiveNow\\\"\\s*:\\s*true|\\\"isLiveContent\\\"\\s*:\\s*true|\\\"isLive\\\"\\s*:\\s*true)/i.test(h);const start=h.match(/\\\"startTimestamp\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"/i)?.[1]||h.match(/\\\"actualStartTime\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"/i)?.[1]||null;return{youtube_id:id,title:o.title||`YouTube video ${id}`,channel_title:o.author_name||'YouTube',thumbnail_url:o.thumbnail_url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,duration_seconds:duration,is_live:live,live_start_time:start};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const u=await getUser(req);if(!u)return json({error:'Authentication required.'},401);const d=db();const b=await req.json().catch(()=>({}));const a=String(b.action||'');
if(a==='register_view'){const vid=String(b.video_id||'');if(!vid)return json({error:'Video is required.'},400);await d.from('video_views').upsert({video_id:vid,user_id:u.id,last_viewed_at:new Date().toISOString()},{onConflict:'video_id,user_id'});const{count}=await d.from('video_views').select('*',{count:'exact',head:true}).eq('video_id',vid);await d.from('videos').update({view_count:count||0}).eq('id',vid);return json({view_count:count||0});}
if(a==='set_duration'){const vid=String(b.video_id||''),seconds=Math.max(0,Math.floor(Number(b.duration_seconds)||0));if(!vid||!seconds)return json({error:'Invalid duration.'},400);await d.from('videos').update({duration_seconds:seconds,is_live:false,live_start_time:null,updated_at:new Date().toISOString()}).eq('id',vid);return json({duration_seconds:seconds});}
if(a==='watch_progress'){const vid=String(b.video_id||''),sec=Math.max(0,Math.floor(Number(b.seconds)||0)),dur=Math.max(0,Math.floor(Number(b.duration)||0));if(!vid)return json({error:'Video is required.'},400);const{data:old}=await d.from('watch_history').select('watched_seconds,completed').eq('user_id',u.id).eq('video_id',vid).maybeSingle();const watched=Math.max(sec,Number(old?.watched_seconds||0));const completed=Boolean(old?.completed)||(dur>0&&watched>=Math.floor(dur*.9));await d.from('watch_history').upsert({user_id:u.id,video_id:vid,watched_seconds:watched,completed,last_watched_at:new Date().toISOString()},{onConflict:'user_id,video_id'});return json({watched_seconds:watched,completed});}
if(a==='comment_add'){const vid=String(b.video_id||''),text=String(b.body||'').trim();if(!vid||!text||text.length>2000)return json({error:'Invalid comment.'},400);const{data,error}=await d.from('video_comments').insert({video_id:vid,user_id:u.id,body:text}).select('id,video_id,user_id,body,like_count,dislike_count,created_at,updated_at').single();if(error)return json({error:error.message},400);const{count}=await d.from('video_comments').select('*',{count:'exact',head:true}).eq('video_id',vid);await d.from('videos').update({comment_count:count||0}).eq('id',vid);return json({comment:data,comment_count:count||0});}
if(a==='comment_delete'){const cid=String(b.comment_id||'');if(!cid)return json({error:'Comment is required.'},400);const{data:c}=await d.from('video_comments').select('video_id,user_id').eq('id',cid).maybeSingle();if(!c)return json({error:'Comment not found.'},404);if(c.user_id!==u.id&&!(await isAdmin(u.id,d)))return json({error:'Not allowed.'},403);await d.from('comment_reactions').delete().eq('comment_id',cid);const{error}=await d.from('video_comments').delete().eq('id',cid);if(error)return json({error:error.message},400);const{count}=await d.from('video_comments').select('*',{count:'exact',head:true}).eq('video_id',c.video_id);await d.from('videos').update({comment_count:count||0}).eq('id',c.video_id);return json({ok:true,comment_count:count||0});}
if(a==='comment_reaction'||a==='video_reaction'){const table=a==='comment_reaction'?'comment_reactions':'video_reactions';const key=a==='comment_reaction'?'comment_id':'video_id';const item=String(b[key]||''),reaction=String(b.reaction||'');if(!item||!['like','dislike'].includes(reaction))return json({error:'Invalid reaction.'},400);const{data:old}=await d.from(table).select('reaction').eq(key,item).eq('user_id',u.id).maybeSingle();if(old?.reaction===reaction)await d.from(table).delete().eq(key,item).eq('user_id',u.id);else await d.from(table).upsert({[key]:item,user_id:u.id,reaction},{onConflict:`${key},user_id`});const{count:likes}=await d.from(table).select('*',{count:'exact',head:true}).eq(key,item).eq('reaction','like');const{count:dislikes}=await d.from(table).select('*',{count:'exact',head:true}).eq(key,item).eq('reaction','dislike');if(a==='comment_reaction')await d.from('video_comments').update({like_count:likes||0,dislike_count:dislikes||0}).eq('id',item);else await d.from('videos').update({like_count:likes||0,dislike_count:dislikes||0}).eq('id',item);return json({my_reaction:old?.reaction===reaction?null:reaction,like_count:likes||0,dislike_count:dislikes||0});}
if(a==='save_video'){const vid=String(b.video_id||'');const{data:old}=await d.from('saved_videos').select('video_id').eq('video_id',vid).eq('user_id',u.id).maybeSingle();if(old)await d.from('saved_videos').delete().eq('video_id',vid).eq('user_id',u.id);else await d.from('saved_videos').insert({video_id:vid,user_id:u.id});const{count}=await d.from('saved_videos').select('*',{count:'exact',head:true}).eq('video_id',vid);await d.from('videos').update({save_count:count||0}).eq('id',vid);return json({saved:!old,save_count:count||0});}
if(a==='share_video'){const vid=String(b.video_id||'');const{data:old}=await d.from('video_shares').select('video_id').eq('video_id',vid).eq('user_id',u.id).maybeSingle();if(!old)await d.from('video_shares').insert({video_id:vid,user_id:u.id});const{count}=await d.from('video_shares').select('*',{count:'exact',head:true}).eq('video_id',vid);await d.from('videos').update({share_count:count||0}).eq('id',vid);return json({share_count:count||0});}
if(a==='follow_channel'){const ch=String(b.channel_title||'').trim();if(!ch)return json({error:'Channel is required.'},400);const{data:old}=await d.from('channel_follows').select('channel_title').eq('user_id',u.id).eq('channel_title',ch).maybeSingle();if(old)await d.from('channel_follows').delete().eq('user_id',u.id).eq('channel_title',ch);else await d.from('channel_follows').insert({user_id:u.id,channel_title:ch});return json({following:!old});}
if(a==='admin_add_video'){if(!(await isAdmin(u.id,d)))return json({error:'Admin access required.'},403);const id=parseId(String(b.youtube_id||''));if(!id)return json({error:'Invalid YouTube ID.'},400);const m=await ytMeta(id);const{data,error}=await d.from('videos').insert({...m,added_by:u.id}).select('*').single();if(error)return json({error:error.message},400);return json({video:data});}
if(a==='admin_update_video'){if(!(await isAdmin(u.id,d)))return json({error:'Admin access required.'},403);const videoId=String(b.video_id||'');const patch:any={};if(typeof b.title==='string'&&b.title.trim())patch.title=b.title.trim();if(typeof b.youtube_id==='string'&&b.youtube_id.trim()){const id=parseId(b.youtube_id);if(!id)return json({error:'Invalid YouTube ID.'},400);Object.assign(patch,await ytMeta(id))}const{data,error}=await d.from('videos').update(patch).eq('id',videoId).select('*').single();if(error)return json({error:error.message},400);return json({video:data});}
if(a==='admin_delete_video'){if(!(await isAdmin(u.id,d)))return json({error:'Admin access required.'},403);const{error}=await d.from('videos').delete().eq('id',String(b.video_id||''));if(error)return json({error:error.message},400);return json({ok:true});}
return json({error:'Unknown action.'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Unexpected server error.'},500)}});
