import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function getUser(req:Request){const a=req.headers.get('Authorization');if(!a)return null;const c=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:a}}});return (await c.auth.getUser()).data.user||null;}
const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
function parseId(input:string){const v=input.trim();if(/^[A-Za-z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v);if(u.hostname==='youtu.be')return u.pathname.slice(1).split('/')[0]||null;if(u.hostname.endsWith('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v');if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||null;if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||null;}}catch{}return null;}
async function admin(userId:string,s:any){const{data}=await s.from('profiles').select('is_admin').eq('id',userId).maybeSingle();return !!data?.is_admin;}
async function resolveYouTube(id:string){const w=`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`;const r=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(w)}&format=json`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('This YouTube video could not be resolved.');const meta=await r.json();const page=await fetch(w,{headers:{'User-Agent':'Mozilla/5.0 Chrome/131 Safari/537.36','Accept-Language':'en-US,en;q=0.9'}});const html=page.ok?await page.text():'';let duration=0;for(const p of [/\"lengthSeconds\":\"(\d+)\"/i,/\"lengthSeconds\":(\d+)/i,/lengthSeconds\\\":\\\"(\d+)\\\"/i,/lengthSeconds\\\":(\d+)/i,/\"approxDurationMs\":\"(\d+)\"/i]){const m=html.match(p);if(m){duration=p.source.includes('approxDurationMs')?Math.round(Number(m[1])/1000):Number(m[1]);if(duration>0)break;}}return{youtube_id:id,title:meta.title||`YouTube video ${id}`,channel_title:meta.author_name||'YouTube',thumbnail_url:meta.thumbnail_url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,duration_seconds:duration};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const user=await getUser(req);if(!user)return json({error:'Authentication required.'},401);const b=await req.json().catch(()=>({})),a=String(b.action||''),s=db();
if(a==='resolve_video'){if(!(await admin(user.id,s)))return json({error:'Admin access required.'},403);const id=parseId(String(b.youtube_id||''));if(!id)return json({error:'Enter a valid YouTube video ID.'},400);return json({video:await resolveYouTube(id)});}
if(a==='admin_add_video'){if(!(await admin(user.id,s)))return json({error:'Admin access required.'},403);const id=parseId(String(b.youtube_id||''));if(!id)return json({error:'Enter a valid YouTube video ID.'},400);const m=await resolveYouTube(id);const{data,error}=await s.from('videos').insert({...m,added_by:user.id}).select('*').single();if(error)return json({error:error.code==='23505'?'That video is already in the feed.':error.message},400);return json({video:data});}
if(a==='admin_update_video'){if(!(await admin(user.id,s)))return json({error:'Admin access required.'},403);const id=String(b.video_id||''),patch:any={};if(typeof b.title==='string'&&b.title.trim())patch.title=b.title.trim();if(typeof b.youtube_id==='string'){const yid=parseId(b.youtube_id);if(!yid)return json({error:'Invalid YouTube ID.'},400);Object.assign(patch,await resolveYouTube(yid));}const{data,error}=await s.from('videos').update(patch).eq('id',id).select('*').single();if(error)return json({error:error.message},400);return json({video:data});}
if(a==='admin_delete_video'){if(!(await admin(user.id,s)))return json({error:'Admin access required.'},403);const{error}=await s.from('videos').delete().eq('id',String(b.video_id||''));if(error)return json({error:error.message},400);return json({ok:true});}
if(a==='video_reaction'){const vid=String(b.video_id||''),reaction=String(b.reaction||'');if(!vid||!['like','dislike'].includes(reaction))return json({error:'Invalid reaction.'},400);const{data:ex}=await s.from('video_reactions').select('reaction').eq('video_id',vid).eq('user_id',user.id).maybeSingle();if(ex?.reaction===reaction)await s.from('video_reactions').delete().eq('video_id',vid).eq('user_id',user.id);else await s.from('video_reactions').upsert({video_id:vid,user_id:user.id,reaction},{onConflict:'video_id,user_id'});const{count:likes}=await s.from('video_reactions').select('*',{count:'exact',head:true}).eq('video_id',vid).eq('reaction','like');const{count:dislikes}=await s.from('video_reactions').select('*',{count:'exact',head:true}).eq('video_id',vid).eq('reaction','dislike');await s.from('videos').update({like_count:likes||0,dislike_count:dislikes||0}).eq('id',vid);return json({my_reaction:ex?.reaction===reaction?null:reaction,like_count:likes||0,dislike_count:dislikes||0});}
if(a==='save_video'){const vid=String(b.video_id||''),{data:ex}=await s.from('saved_videos').select('video_id').eq('video_id',vid).eq('user_id',user.id).maybeSingle();if(ex)await s.from('saved_videos').delete().eq('video_id',vid).eq('user_id',user.id);else await s.from('saved_videos').insert({video_id:vid,user_id:user.id});const{count}=await s.from('saved_videos').select('*',{count:'exact',head:true}).eq('video_id',vid);await s.from('videos').update({save_count:count||0}).eq('id',vid);return json({saved:!ex,save_count:count||0});}
if(a==='share_video'){const vid=String(b.video_id||''),{data:ex}=await s.from('video_shares').select('video_id').eq('video_id',vid).eq('user_id',user.id).maybeSingle();if(!ex)await s.from('video_shares').insert({video_id:vid,user_id:user.id});const{count}=await s.from('video_shares').select('*',{count:'exact',head:true}).eq('video_id',vid);await s.from('videos').update({share_count:count||0}).eq('id',vid);return json({share_count:count||0});}
if(a==='comment_add'){const vid=String(b.video_id||''),text=String(b.body||'').trim();if(!vid||!text||text.length>2000)return json({error:'Invalid comment.'},400);const{data,error}=await s.from('video_comments').insert({video_id:vid,user_id:user.id,body:text}).select('id,video_id,user_id,body,like_count,dislike_count,created_at,updated_at').single();if(error)return json({error:error.message},400);const{count}=await s.from('video_comments').select('*',{count:'exact',head:true}).eq('video_id',vid);await s.from('videos').update({comment_count:count||0}).eq('id',vid);return json({comment:data,comment_count:count||0});}
if(a==='comment_reaction'){const cid=String(b.comment_id||''),reaction=String(b.reaction||'');if(!cid||!['like','dislike'].includes(reaction))return json({error:'Invalid reaction.'},400);const{data:ex}=await s.from('comment_reactions').select('reaction').eq('comment_id',cid).eq('user_id',user.id).maybeSingle();if(ex?.reaction===reaction)await s.from('comment_reactions').delete().eq('comment_id',cid).eq('user_id',user.id);else await s.from('comment_reactions').upsert({comment_id:cid,user_id:user.id,reaction},{onConflict:'comment_id,user_id'});const{count:likes}=await s.from('comment_reactions').select('*',{count:'exact',head:true}).eq('comment_id',cid).eq('reaction','like');const{count:dislikes}=await s.from('comment_reactions').select('*',{count:'exact',head:true}).eq('comment_id',cid).eq('reaction','dislike');await s.from('video_comments').update({like_count:likes||0,dislike_count:dislikes||0}).eq('id',cid);return json({my_reaction:ex?.reaction===reaction?null:reaction,like_count:likes||0,dislike_count:dislikes||0});}
if(a==='watch_progress'){const vid=String(b.video_id||''),seconds=Math.max(0,Math.floor(Number(b.seconds)||0)),duration=Math.max(0,Math.floor(Number(b.duration)||0));if(!vid)return json({error:'Video is required.'},400);const{data:ex}=await s.from('watch_history').select('watched_seconds,completed').eq('user_id',user.id).eq('video_id',vid).maybeSingle();const watched=Math.max(seconds,Number(ex?.watched_seconds||0));const completed=Boolean(ex?.completed)||(duration>0&&watched/duration>=0.9);await s.from('watch_history').upsert({user_id:user.id,video_id:vid,watched_seconds:watched,completed,last_watched_at:new Date().toISOString()},{onConflict:'user_id,video_id'});let counted=false;if(watched>=30){const{data:view}=await s.from('video_views').select('video_id').eq('video_id',vid).eq('user_id',user.id).maybeSingle();if(!view){await s.from('video_views').insert({video_id:vid,user_id:user.id,last_viewed_at:new Date().toISOString()});counted=true;}}return json({watched_seconds:watched,completed,counted});}
if(a==='refresh_duration'){const vid=String(b.video_id||''),{data:video}=await s.from('videos').select('youtube_id').eq('id',vid).single();if(!video)return json({error:'Video not found.'},404);const meta=await resolveYouTube(video.youtube_id);if(meta.duration_seconds>0)await s.from('videos').update({duration_seconds:meta.duration_seconds}).eq('id',vid);return json({duration_seconds:meta.duration_seconds});}
return json({error:'Unknown action.'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Unexpected server error.'},500)}});
